# This is a basic workflow to help you get started with Actions

name: LintCheck

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events to develop branch or push the main branch
  # mainブランチに直でpushした場合を想定
  push:
    branches: [main]
  pull_request:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install node packages
      - name: install packages
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Run a lint
        run: yarn lint
